/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Eventos;
import Modelo.Producto;
import Modelo.ProductoDao;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javaswingdev.Notification;

/**
 *
 * @author Jonathan Gil
 */
public class cantidadProductos extends javax.swing.JDialog {

    Eventos event = new Eventos();
    ProductoDao productoDao = new ProductoDao();
    
    double cantidad, cantidadModificada, precioUnitario;
    String codigo;
    int indicador;
    boolean accionRealizada=false;
    Producto p;
    DecimalFormat formateador = new DecimalFormat("#,###,##0.00");   
        DecimalFormat formato = new DecimalFormat("0.00");
    
            
    public cantidadProductos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Seticon();
        txtPrecioUnitario.setBackground(new Color(240,240,240));
        txtPiezas.setBackground(new Color(240,240,240));
        txtImporte.setBackground(new Color(240,240,240));
        txtResiduo.setBackground(new Color(240,240,240));
       
    }
    
    public void vaciarProducto(int indicador, double cantidad, double precioUnitario, String codigo){
        this.indicador=indicador;
        this.cantidad=cantidad;
        this.precioUnitario=precioUnitario;
        this.codigo=codigo;
        p = productoDao.BuscarPorCodigo(codigo);
        txtPrecioUnitario.setText("$"+formateador.format(precioUnitario));
        txtPiezas.setText(formato.format(cantidad));
        txtImporte.setText("$"+formateador.format(precioUnitario*cantidad));
        if(indicador==1){ //descuento
           txtTitulo.setText("Descuento por articulo");
           this.setTitle("Punto de venta - Descuento por articulo");
           txtResiduo.setToolTipText("Saldo final");
          txtMonto.setToolTipText("Cantidad a descontar");
        } 
        if(indicador==2){ //bonificacion
           txtTitulo.setText("Bonificación por articulo");
           this.setTitle("Punto de venta - Bonificación por articulo");
             txtResiduo.setToolTipText("Saldo final");
             txtMonto.setToolTipText("Cantidad a bonificar");
        } 
        if(indicador==3){ //devolucion
           txtTitulo.setText("Cantidad de piezas");
           this.setTitle("Punto de venta - Cantidad de piezas");
           lbLimpio.setText("Piezas");
          txtMonto.setToolTipText("Cantidad de piezas a regresar");
           lbCantidad.setText("Subtotal");
           txtResiduo.setToolTipText("Importe por piezas devueltas");
        } 
    }
    

    
    public void eventoEnter(){
         if(!"".equals(txtMonto.getText())){
            if(!txtMonto.getText().endsWith(".")){
                cantidadModificada = Double.parseDouble(txtMonto.getText());
                if(indicador==3){
                     if(Double.parseDouble(txtMonto.getText())>cantidad){
                         Notification panel = new Notification(new javax.swing.JFrame(), Notification.Type.WARNING, Notification.Location.TOP_CENTER, "Cantidad no valida");
                                 panel.showNotification();   
                     }else{
                         accionRealizada=true;
                         dispose();
                     }
                  }else{
                    if(Double.parseDouble(txtMonto.getText())>(precioUnitario*cantidad)){
                     Notification panel = new Notification(new javax.swing.JFrame(), Notification.Type.WARNING, Notification.Location.TOP_CENTER, "Cantidad no valida");
                                 panel.showNotification();   
                    }else{
                         accionRealizada=true;
                         dispose();
                    }
                }         
            }else{
            Notification panel = new Notification(new javax.swing.JFrame(), Notification.Type.WARNING, Notification.Location.TOP_CENTER, "No se ha ingresado ninguna cantidad");
                                 panel.showNotification();
        }
         }else{
            Notification panel = new Notification(new javax.swing.JFrame(), Notification.Type.WARNING, Notification.Location.TOP_CENTER, "No se ha ingresado ninguna cantidad");
                                 panel.showNotification();
        }
        
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        panelGuardar = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JLabel();
        panelCancelar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JLabel();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtPiezas = new javax.swing.JTextField();
        txtImporte = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtResiduo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbLimpio = new javax.swing.JLabel();
        lbCantidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 255));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Agregar cantidad de productos");
        jPanel4.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 20, 200, -1));

        jLabel26.setBackground(new java.awt.Color(0, 0, 204));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 255));
        jLabel26.setText("¿Está seguro de ejecutar esta acción? ");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        panelGuardar.setBackground(new java.awt.Color(255, 255, 255));
        panelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelGuardarMouseEntered(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(153, 204, 255));
        btnGuardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar nota 2.png"))); // NOI18N
        btnGuardar.setToolTipText("ENTER - Realizar acción");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuardarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelGuardarLayout = new javax.swing.GroupLayout(panelGuardar);
        panelGuardar.setLayout(panelGuardarLayout);
        panelGuardarLayout.setHorizontalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGuardarLayout.setVerticalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel4.add(panelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 50, 50));

        panelCancelar.setBackground(new java.awt.Color(255, 255, 255));
        panelCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCancelarMouseEntered(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen5.png"))); // NOI18N
        btnCancelar.setToolTipText("ESCAPE - Cancelar acción y salir");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelCancelarLayout = new javax.swing.GroupLayout(panelCancelar);
        panelCancelar.setLayout(panelCancelarLayout);
        panelCancelarLayout.setHorizontalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCancelarLayout.setVerticalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel4.add(panelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 50, 50));

        txtPrecioUnitario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPrecioUnitario.setToolTipText("Precio unitario");
        txtPrecioUnitario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPrecioUnitario.setEnabled(false);
        jPanel4.add(txtPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 135, -1));

        txtPiezas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPiezas.setToolTipText("cantidad vendido del producto");
        txtPiezas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPiezas.setEnabled(false);
        txtPiezas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPiezasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPiezasKeyTyped(evt);
            }
        });
        jPanel4.add(txtPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 135, -1));

        txtImporte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtImporte.setToolTipText("Importe por el producto");
        txtImporte.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtImporte.setEnabled(false);
        txtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImporteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImporteKeyTyped(evt);
            }
        });
        jPanel4.add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 135, -1));

        txtMonto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMonto.setToolTipText("Monto");
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMontoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });
        jPanel4.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 135, -1));

        txtResiduo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtResiduo.setToolTipText("Fecha de cancelación");
        txtResiduo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtResiduo.setEnabled(false);
        jPanel4.add(txtResiduo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 135, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Precio Unitario");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 43, 90, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Cantidad");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 73, 90, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Importe");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 103, 90, -1));

        lbLimpio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbLimpio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbLimpio.setText("Monto");
        jPanel4.add(lbLimpio, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 133, 90, -1));

        lbCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCantidad.setText("Restante");
        jPanel4.add(lbCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 163, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        eventoEnter();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        panelGuardar.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        panelGuardar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyPressed
        int codigo=evt.getKeyCode();
        switch(codigo){
            case KeyEvent.VK_ENTER:
            eventoEnter();
            break;

            case KeyEvent.VK_ESCAPE:
            dispose();
            break;

        }
    }//GEN-LAST:event_btnGuardarKeyPressed

    private void panelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelGuardarMouseClicked

    private void panelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelGuardarMouseEntered

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        panelCancelar.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        panelCancelar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarKeyPressed
        int codigo=evt.getKeyCode();
        switch(codigo){
            case KeyEvent.VK_ENTER:
            eventoEnter();
            break;

            case KeyEvent.VK_ESCAPE:
            dispose();
            break;

        }
    }//GEN-LAST:event_btnCancelarKeyPressed

    private void panelCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelarMouseClicked

    }//GEN-LAST:event_panelCancelarMouseClicked

    private void panelCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCancelarMouseEntered

    private void txtPiezasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPiezasKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPiezasKeyReleased

    private void txtPiezasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPiezasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPiezasKeyTyped

    private void txtImporteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteKeyReleased
        int codigo=evt.getKeyCode();
        switch(codigo){
            case KeyEvent.VK_ENTER:
            eventoEnter();
            break;

            case KeyEvent.VK_ESCAPE:
            dispose();
            break;

        }
    }//GEN-LAST:event_txtImporteKeyReleased

    private void txtImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImporteKeyTyped

    private void txtMontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyReleased
        if(!"".equals(txtMonto.getText())){
            if(!txtMonto.getText().endsWith(".")){
        if(indicador==3){
            double nuevoImporte = precioUnitario * Double.parseDouble(txtMonto.getText());
            txtResiduo.setText("$"+formateador.format(nuevoImporte));
         }else{
             double nuevoImporte =(precioUnitario*cantidad)-Double.parseDouble(txtMonto.getText()); 
            txtResiduo.setText("$"+formateador.format(nuevoImporte));
         } 
        }else{
         txtResiduo.setText("");
        }
        }else{
         txtResiduo.setText("");
        }
        
        int codigo=evt.getKeyCode();
        switch(codigo){
            case KeyEvent.VK_ENTER:
            eventoEnter();
            break;

            case KeyEvent.VK_ESCAPE:
            dispose();
            break;

        }
    }//GEN-LAST:event_txtMontoKeyReleased

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
     if(p.getTipoVenta().equals("Pieza") && p.getTipoVenta().equals("Servicio")) event.numberKeyPress(evt);
     else event.numberDecimalKeyPress(evt, txtMonto);
    }//GEN-LAST:event_txtMontoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cantidadProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cantidadProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cantidadProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cantidadProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cantidadProductos dialog = new cantidadProductos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbLimpio;
    private javax.swing.JPanel panelCancelar;
    private javax.swing.JPanel panelGuardar;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtPiezas;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtResiduo;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables

 private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Program Files (x86)\\AppPinturasOssel\\Iconos\\Osel.jpg"));
   }

}
