/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.CorteDiarioDao;
import Modelo.Empleados;
import Modelo.Gastos;
import Modelo.GastosDao;
import static Vista.vistaVenta.isNumeric;
import com.raven.swing.Table;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.SwingConstants;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class vistaGastos extends javax.swing.JDialog {

    DefaultTableModel modelo = new DefaultTableModel();
    GastosDao gastos = new GastosDao();
    CorteDiarioDao corteDao = new CorteDiarioDao();
    int fila = -1;
    DecimalFormat formateador = new DecimalFormat("#,###,##0.00");
    String fecha = corteDao.getDia();
    Empleados e;

    public void vaciarEmpleado(Empleados e) {
        this.e = e;
    }

    public vistaGastos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(200, 50);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle("Punto de venta - Gastos");
        Seticon();

        jScrollPane9.getViewport().setBackground(new Color(204, 204, 204));
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        DefaultTableCellRenderer tcrDerecha = new DefaultTableCellRenderer();

        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        tcrDerecha.setHorizontalAlignment(SwingConstants.RIGHT);
        TablaDeGastos.getColumnModel().getColumn(0).setCellRenderer(tcr);
        TablaDeGastos.getColumnModel().getColumn(1).setCellRenderer(tcr);
        TablaDeGastos.getColumnModel().getColumn(2).setCellRenderer(tcr);
        TablaDeGastos.getColumnModel().getColumn(3).setCellRenderer(tcrDerecha);
        TablaDeGastos.getColumnModel().getColumn(4).setCellRenderer(tcr);
        TablaDeGastos.getColumnModel().getColumn(5).setCellRenderer(tcr);

        ((DefaultTableCellRenderer) TablaDeGastos.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);
        listarGastosTodos();

        LocalDate fechaActual = LocalDate.now();
        java.sql.Date fechaSQL = java.sql.Date.valueOf(fechaActual);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        //fecha = fechaSQL.toLocalDate().format(formatter);
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent e) {
                Point currentLocation = getLocation();
                if (currentLocation.y < 50) {
                    setLocation(200, 50);
                };

            }
        });

    }

    public void listarGastosTodos() {
        List<Gastos> lsGastos = gastos.listarGastos();//Obtenemos gastos de la BD
        modelo = (DefaultTableModel) TablaDeGastos.getModel();
        Object[] ob = new Object[6];
        for (int i = lsGastos.size() - 1; i >= 0; i--) { //vaciamos los datos en la tabla
            ob[0] = lsGastos.get(i).getId();
            ob[1] = lsGastos.get(i).getComprobante();
            ob[2] = lsGastos.get(i).getDescripcion();
            ob[3] = "$" + formateador.format(lsGastos.get(i).getPrecio());
            ob[4] = lsGastos.get(i).getFormaPago();
            ob[5] = fechaFormatoCorrecto(lsGastos.get(i).getFecha());
            modelo.addRow(ob);
        }
        TablaDeGastos.setModel(modelo);
    }

    public void LimpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    public void eventoF1() {
        vistaGasto vg = new vistaGasto(new javax.swing.JFrame(), true);
        vg.setVisible(true);
        if (vg.indicador == true) {
            LimpiarTabla();
            listarGastosTodos();
        }
    }

    public void eventoF2() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new textfield.TextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TablaDeGastos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GASTOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(667, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 960, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setLabelText("Buscar gasto");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, 410, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 940, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaDeGastos = new Table();
        TablaDeGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Comprobante", "Descripción", "Total", "FormaPago", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaDeGastos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TablaDeGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDeGastosMouseClicked(evt);
            }
        });
        TablaDeGastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TablaDeGastosKeyPressed(evt);
            }
        });
        jScrollPane9.setViewportView(TablaDeGastos);
        if (TablaDeGastos.getColumnModel().getColumnCount() > 0) {
            TablaDeGastos.getColumnModel().getColumn(0).setResizable(false);
            TablaDeGastos.getColumnModel().getColumn(0).setPreferredWidth(2);
            TablaDeGastos.getColumnModel().getColumn(1).setResizable(false);
            TablaDeGastos.getColumnModel().getColumn(1).setPreferredWidth(180);
            TablaDeGastos.getColumnModel().getColumn(2).setResizable(false);
            TablaDeGastos.getColumnModel().getColumn(2).setPreferredWidth(180);
            TablaDeGastos.getColumnModel().getColumn(3).setResizable(false);
            TablaDeGastos.getColumnModel().getColumn(3).setPreferredWidth(10);
            TablaDeGastos.getColumnModel().getColumn(4).setResizable(false);
            TablaDeGastos.getColumnModel().getColumn(4).setPreferredWidth(10);
            TablaDeGastos.getColumnModel().getColumn(5).setResizable(false);
            TablaDeGastos.getColumnModel().getColumn(5).setPreferredWidth(15);
        }

        jPanel4.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, 920, 460));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 940, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaDeGastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDeGastosMouseClicked
        if (evt.getClickCount() == 2) {
            fila = TablaDeGastos.rowAtPoint(evt.getPoint());
        }
    }//GEN-LAST:event_TablaDeGastosMouseClicked

    private void TablaDeGastosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaDeGastosKeyPressed
        int codigo = evt.getKeyCode();
        switch (codigo) {
            case KeyEvent.VK_F2:
                eventoF2();
                break;

            case KeyEvent.VK_ESCAPE:
                dispose();
                break;
        }
    }//GEN-LAST:event_TablaDeGastosKeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        int codigo = evt.getKeyCode();
        switch (codigo) {
            case KeyEvent.VK_F2:
                eventoF2();
                break;

            case KeyEvent.VK_ESCAPE:
                dispose();
                break;
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        fila = -1;
        LimpiarTabla();
        if (!"".equals(jTextField1.getText())) {
            if (isNumeric(jTextField1.getText()) == true) {
                Gastos alistar = gastos.BuscarPorCodigo(Integer.parseInt(jTextField1.getText()));
                if (alistar.getId() == 0) {
                    modelo = (DefaultTableModel) TablaDeGastos.getModel();
                    TablaDeGastos.setModel(modelo);
                } else {
                    modelo = (DefaultTableModel) TablaDeGastos.getModel();
                    Object[] ob = new Object[5];
                    ob[0] = alistar.getId();
                    ob[1] = alistar.getComprobante();
                    ob[2] = alistar.getDescripcion();
                    ob[3] = alistar.getPrecio();
                    ob[4] = alistar.getFormaPago();
                    ob[5] = fechaFormatoCorrecto(alistar.getFecha());
                    modelo.addRow(ob);

                    TablaDeGastos.setModel(modelo);
                }
            } else {
                List<Gastos> lsGastos = gastos.buscarLetra(jTextField1.getText());

                modelo = (DefaultTableModel) TablaDeGastos.getModel();
                Object[] ob = new Object[6];
                for (int i = 0; i < lsGastos.size(); i++) {
                    ob[0] = lsGastos.get(i).getId();
                    ob[1] = lsGastos.get(i).getComprobante();
                    ob[2] = lsGastos.get(i).getDescripcion();
                    ob[3] = "$" + formateador.format(lsGastos.get(i).getPrecio());
                    ob[4] = lsGastos.get(i).getFormaPago();
                    ob[5] = fechaFormatoCorrecto(lsGastos.get(i).getFecha());
                    modelo.addRow(ob);
                }
                TablaDeGastos.setModel(modelo);
            }
        } else {
            listarGastosTodos();
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistaGastos dialog = new vistaGastos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDeGastos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane9;
    private textfield.TextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Program Files (x86)\\AppPinturasOssel\\Iconos\\Osel.jpg"));
    }

    public java.util.Date StringADate(String cambiar) { //Este metodo te transforma un String a date (dia)
        SimpleDateFormat formato_del_Texto = new SimpleDateFormat("yyyy-MM-dd"); //El formato del string
        Date fechaE = null;
        try {
            fechaE = formato_del_Texto.parse(cambiar);
            return fechaE; //retornamos la fecha
        } catch (ParseException ex) {
            return null;
        }
    }

    public String fechaFormatoCorrecto(String fechaHoy) {
        Date diaActual = StringADate(fechaHoy);
        DateFormat cam = new SimpleDateFormat("dd-MM-yyyy");
        String fechaUsar;
        Date fechaNueva;
        Calendar c = Calendar.getInstance();
        c.setTime(diaActual);
        fechaUsar = cam.format(diaActual);
        return fechaUsar;
    }

}
